[tool.poetry]
name = "renamer"
version = "0.1.0"
description = "cli to help with renaming original ingested files with missing or wrong extension"
authors = ["Claus Juhl Knudsen <cjk@aarhus.dk>"]

[tool.poetry.dependencies]
python = "*"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
renamer = 'renamer:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
